repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.88.0"
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_trivy
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args: ["--lockfile=false", "markdown", "table", "--output-file", "README.md", "./"]
