name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      pythonVersion: "3.12"
      trivyVersion: "0.49.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Python Version
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.pythonVersion }}"
      - name: Pre-commit Cache
        uses: actions/cache@v4
        with:
          key: pre-commit-${{hashFiles('.pre-commit-config.yaml')}}-${{ env.pythonVersion }}
          path: ~/.cache/pre-commit
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v${{ env.trivyVersion }}/trivy_${{ env.trivyVersion }}_Linux-64bit.deb
          sudo dpkg -i trivy_${{ env.trivyVersion }}_Linux-64bit.deb
          trivy -v
      - name: Install Pre-commit
        run: python -m pip install --upgrade pre-commit
      - name: Run Pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
